### ISSUE TITLE
Playground error when "Generate key and publish introduction"

### ISSUE THREAD

**Issue by mdroidian** [vemonet/nanopub-rs#10]
After logging in with ORCID, the [playground](https://vemonet.github.io/nanopub-rs/playground.html) is throwing the following error

`Error publishing Nanopub Introduction: Error sendind the HTTP request: error sending request`

after clicking on the `Generate key and publish introduction` button.

Chrome console shows a CORS error:

![image](https://github.com/user-attachments/assets/319dbb67-d0c5-446f-b522-8955a3a89d6b)

This was repo'd with with two different users/ORCID's.

**Comment by mdroidian** [comment]
Here's a video showing the whole Network tab

https://www.loom.com/share/3ec3e0f138824da8b412d33ef8263a2c

**Comment by tkuhn** [comment]
OK, thanks. I could reproduce this.

It seems to require a `Access-Control-Allow-Headers` header. I am not sure why this is now necessary. It used to work, so I think it wasn't needed previously.

Anyway, I added this header line to the relevant servers, and I think it should work now. Could you try again?

**Comment by mdroidian** [comment]
Fixed, thanks!
