### ISSUE TITLE
Can't publish two Nanopublications without reloading the page.

### ISSUE THREAD

**Issue by pepoospina** [vemonet/nanopub-rs#5]
Hi, I'm not sure if this is an issue or if I'm missing something related to managing wasm.

If I create a nanopublication, publish it, then create another one and try to publish that one, I get a wasm null pointer error.

This is the code structure:
```ts
        const nanopub =  new Nanopub(rdfStr1);
        nanopubPublished = await nanopub.publish(profile, NANOPUBS_SERVER);

        const nanopub2 = new Nanopub(rdfStr2);;
        const nanopubPublished2 = await nanopub2.publish(
          profile,
          NANOPUBS_SERVER
        );

```

And this is how the both nanopubs and the published one look on the browser console:

![image](https://github.com/vemonet/nanopub-rs/assets/3278772/ac9eee9a-7a0d-4f76-84bb-34e737e55d7e)

And then when I run nanopub2.publish(...) I get the error

```
web.js:870 Uncaught (in promise) Error: null pointer passed to rust
    at imports.wbg.__wbindgen_throw (web.js:870:1)
    at web_bg.6cae08b3ffcfcf4586ae.wasm:0x21a8f8
    at web_bg.6cae08b3ffcfcf4586ae.wasm:0x21a9c0
    at web_bg.6cae08b3ffcfcf4586ae.wasm:0x1a13af
    at Nanopub.publish (web.js:402:1)
    at AppPostPage.tsx:87:1
```

**Comment by vemonet** [comment]
Well spotted @pepoospina, thanks a lot! I forgot to use pointers for the profile in JS bindings, so the profile object was "consumed" on the rust side

I have fixed this in the main branch, it will be fixed at next release

btw if you just `console.log(np)` you'll just see the pointer to the rust object, to see more details about the nanopub use `np.info()`
