### ISSUE TITLE
NpProfile need for orcid

### ISSUE THREAD

**Issue by pepoospina** [vemonet/nanopub-rs#7]
Hi @vemonet, we are finally getting back into the nanopub realm as part of our work.

I wanted to ask you, why do you think the `NpProfile` constructor requires an `orcid_id` and a `name`?

These two values can be securely derived by a consumer application from the public key and the (one of many?) introductory nanopublications.

Such a consumer application should, also, not trust the `orcid_id` or `name` in the pubinfo as they could have been counterfeited.

Similarly, the `introduction_nanopub_uri` seems useful to simplify the task of authenticating a nanopublication, but it may also be considered optional, isn't it?

On the other hand, if the `orcid_id` value was verified by nanopub servers before "accepting" a nanopublication, then it becomes useful indeed. But I understand it's not the case currently.

**Comment by vemonet** [comment]
Hi @pepoospina , indeed that is a good remark

Regarding signing ultimately we just need the private key to be provided in the profile

Currently you can provide an empty string as ORCID and name when defining the profile. But it should be `Option<String>` instead to make it clearer

I'll look into improving this soon (making ORCID and name "officially" optional)

**Comment by vemonet** [comment]
NpProfile can be created without orcid now using the builder pattern (cf. docs)
